spring:
  application:
    name: shop-service
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:8888
#    import: optional:configserver:http://8.222.225.41:8888
server:
  port: 8088

userUrl: http://USER-SERVICE/
categoryUrl: http://CATEGORY-SERVICE/

management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.web: debug
resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED