spring:
  application:
    name: notification-service
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true
server:
  port: 8086

management:
  tracing:
    sampling:
      probability: 1.0