spring:
  application:
    name: product-service
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:8888
#    import: optional:configserver:http://8.222.225.41:8888
server:
  port: 8089

userUrl: http://USER-SERVICE/
categoryUrl: http://CATEGORY-SERVICE/
shopUrl: http://SHOP-SERVICE/
postUrl: http://POST-SERVICE/
logging:
  level:
    org.springframework.web: debug
management:
  tracing:
    sampling:
      probability: 1.0
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      shopService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      postService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED