version: '3'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=tradewise
    ports:
      - '3000:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
